tower:
  appName: "${TOWER_APP_NAME:Nextflow Tower}"
  serverUrl: "${TOWER_SERVER_URL:`http://localhost:8000`}"
  contactEmail: "${TOWER_CONTACT_EMAIL:hello@foo.com}"
---
dataSource:
  pooled: false
#  dbCreate: create
  url: jdbc:mysql://localhost:3306/nf_tower?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: wangyang
  password: 123456
hibernate:
  show_sql: true
  ddl-auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  dialect: io.seqera.util.MySQL55DialectCollateBin
  naming_strategy: io.seqera.util.H8NamingStrategy
grails:
  gorm:
    failOnError: false
---
mail:
  debug: true
  from: me@google.com
  smtp:
    host: localhost
    port: 3025
    user: mr-bean
    password: super-secret
    auth: true
    starttls:
      enable: false
      required: false
    proxy:
      host: proxy.com
      port: 5566
---
auth:
  mail:
    duration: 30m
---
micronaut:
  application:
    name: tower-backend
    instance:
      id: ${random.shortuuid}
  server:
    port: ${MICRONAUT_PORT:8088}
    netty:
    cors:
      enabled: true
  caches:
    rate-limiter:
      expire-after-access: 10m
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginSuccessTargetUrl: "/auth?success=true"
          loginFailureTargetUrl: "/auth?success=false"
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
        generator:
          access-token-expiration: 86400
---